version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - .:/app

  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./public:/usr/share/nginx/html
      - ./certs:/etc/nginx/certs
    ports:
      - "8080:8080"
    depends_on:
      - app
