import "../globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Toaster } from "@/components/ui/toaster"
import { TooltipProvider } from "@/components/ui/tooltip";
import { Providers } from "@/context/Providers";
import { QueryClient, QueryClientProvider } from 'react-query';
import Sidebar from "@/components/sidebar";
import Header from "@/components/header";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Admin Panel",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <Providers>  
      <TooltipProvider>
        <html lang="en">
          <body className={inter.className}>
            <div className="flex h-full">
              <div className="flex-grow h-full pl-14">
                <Header />
                <main className="h-full">
                  {children}
                </main>
              </div>
              <Sidebar />
            </div>
            <Toaster />
          </body>
        </html>
      </TooltipProvider>
    </Providers>
  );
}